### ISSUE TITLE
Include BaseUrl in client interfaces

### ISSUE THREAD

**Issue by mgierlasinski** [RSuter/NSwag#1024]
This is useful when you want to inject url and you are using interfaces instead of implementations. Currently you have to cast interface to the implementation. I have changed it in my overridden liquid template but it could be in the default one as well.

**Comment by RSuter** [comment]
I'm not sure whether this is good idea... setting the base url should be done at creation time and not later. The client may be reused later and if the url has been changed by a client, this may cause problem... (strange errors, etc.)

But for now, I will add an empty template to the interface tpl so that you can safely add additional code...

**Comment by RSuter** [comment]
Is this ok for you?

**Comment by mgierlasinski** [comment]
Great, thanks. My application allows user to change server url in runtime (before login/after logout), clients are pulled from IoC and it was a bit pain to set this in contructor. But this is specific scenario and that extension template will be ok. By the way, liquid templates are working great :)

**Comment by RSuter** [comment]
Thanks for testing and using NSwag :-). Good to know that everything looks good for you... I'm still cleaning up the templates, they are currently not 100% stable (e.g. file names may change). But I expect no big changes...

**Comment by RSuter** [comment]
Client.Interface.Body available in v11.11.3
