### ISSUE TITLE
Use case scenario for INotifyPropertyChanged in generated DTOs?

### ISSUE THREAD

**Issue by GreenMoose2** [RSuter/NSwag#1274]
Hi,

When using `NSwag.CodeGeneration.CSharp`, the generated client DTOs by default implements `INotifyPropertyChanged` and array type is an `ObservableCollection`.

I am trying to understand the use case for this, are there any examples of concepts when the DTOs' `INotifyPropertyChanged` events are used?

Thanks.

**Comment by RSuter** [comment]
You can use these DTOs directly in XAML based apps with bindings and view models. In most cases this is not needed and you can use Poco instead of Inpc (class style) and change the used collection types...

In the next major version, we will change these defaults. 

See https://github.com/RSuter/NSwag/issues/984
