### ISSUE TITLE
Since version 11.18.5, all the query parameters are not required anymore

### ISSUE THREAD

**Issue by srollinet** [RSuter/NSwag#1556]
Prior to version 11.18.5, all the query parameters were required by default, but it is not the case anymore.

Is this on purpose or is it a regression?

```
        [HttpPut("{id}/camera")]
        public Task AffectCamera(string id, string cameraId)
        {
        }
```

left is 11.18.4 and right is 11.18.5
![image](https://user-images.githubusercontent.com/12350967/44547091-44334880-a71a-11e8-8a43-dce717ef6fb1.png)

**Comment by srollinet** [comment]
You can use this project as an example:

[nswag_consumes_issue.zip](https://github.com/RSuter/NSwag/files/2321417/nswag_consumes_issue.zip)

**Comment by RSuter** [comment]
PR with this breaking change: https://github.com/RSuter/NSwag/pull/1521

**Comment by RSuter** [comment]
I created a PR reverting the change and adding some more unit tests (which are passing with the revert in IsRequired): 
https://github.com/RSuter/NSwag/pull/1558

Operation from the tests: 

    public IActionResult QueryParameter(string queryParameter1, string queryParameter2 = null) => null; 

Here I would expect queryParameter1 to be required and queryParameter2 to be optional, is that also what you expect @srollinet?

The problem is that the current ASP.NET Core API Explorer implementation does not handle parameters in this way (both are optional). I think this should be changed... what do you think @paranvkm? Or how can queryParameter1 be made required? Via attribute? 

Maybe we should create a table with all possible param types + scenarios and define in which case they are required or optional?

**Comment by pranavkm** [comment]
`BindRequired` is the attribute you'd use to mark it as "required". For action parameters, we rely on it to determine if MVC will issue a validation error if we could not bind the value, so it seemed appropriate to use it in this case.

> Maybe we should create a table with all possible param types + scenarios and define in which case they are required or optional?

Yeah, I could do that and maybe we can come up something that's less surprising. cc @rynowak \ @dougbu

**Comment by RSuter** [comment]
Thanks Pranav, but this doesnt seem to work: 

![image](https://user-images.githubusercontent.com/2603405/44685917-f2a5f900-aa4c-11e8-9051-6e982bb40b8a.png)

My problem with the current handling is that almost all parameters are optional, which is bad in the specs because they produce "ugly" code, i.e. nullable parameters and such... so the only solution would be to add lots of BindRequired attribute (which probably not a lot of users know about) - which is also not very nice.

I'm wondering what's the best solution here to have a nice convention and avoid breaking everyone?

**Comment by pranavkm** [comment]
> Thanks Pranav, but this doesnt seem to work:

It also effectively requires 2.1 compat behavior. Perhaps you don't have it set? That said, I do agree, the defaults are less than optimal. We'd definitely want the behavior to be more intuitive with fewer attributes. Let me have a chat with the folks here and I could get back. In the meanwhile, reverting your PR sounds good.

**Comment by dougbu** [comment]
> Maybe we should create a table with all possible param types + scenarios and define in which case they are required or optional?

We unfortunately need to have loads of cases in the proposed table because many corner cases exist. For example `[BindRequired]` was, when introduced, applicable only to properties of a complex type. A collection or a collection property still ignores `[BindRequired]` (see aspnet/Mvc#8180).

(Small aside: `[BindRequired]` doesn't result in a "validation error" and actually happens long before the validation phase begins.)

The confusions with `[Required]` relate to (a) the attribute itself silently ignoring value types other than `Nullable<T>` and (b) MVC ignoring the attribute for top-level complex and collection types (we're planning an analyzer for this, see aspnet/Mvc#7415).

> My problem with the current handling is that almost all parameters are optional

For MVC, it is the case that most parameters are optional. `[ApiController]` changes that somewhat e.g. it marks more parameters as `[FromBody]` which implicitly means they're required. But, as @pranavkm notes, that doesn't really solve the issue completely.

**Comment by RSuter** [comment]
@Kahbazi I have to revert the recent change to the IsRequired until we figure out how to handle this case... until then, you can implement a custom operation processor and modify the required properties: https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors

**Comment by RSuter** [comment]
Reverted in v11.19.1, opening a new issue to track this problem.

**Comment by RSuter** [comment]
Created new issue: https://github.com/RSuter/NSwag/issues/1599

**Comment by RSuter** [comment]
IMPORTANT: In the next version (v11.20.0), NSwag will use the api explorer isrequired handling... To keep current behavior, set RequireParametersWithoutDefault to true.
