### ISSUE TITLE
Backslashes in API string enums

### ISSUE THREAD

**Issue by plk** [RSuter/NSwag#1855]
I have a string enum in my spec which NSwag is converting into an enum using the `EnuMember(Value ...)` attribute. The strings have backslashes and these aren't converted by NSwag (forward slash is) and so the resulting code is broken. Is there way to customise this without making an external dll and using `propertyNameGeneratorType` etc. in nswag.json when generating the controller?

**Comment by RSuter** [comment]
Either you provide an own IEnumNameGenerator (not possible yet in the ui as you mentioned) or we fix it in the default one: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/DefaultEnumNameGenerator.cs

Fixing it makes sense as it does not break anyone because it produces broken code anyway... 

It would be awesome if you could create a pr with a fix for just this case...

**Comment by plk** [comment]
I submitted a pull request - I assume it's as simple as I think it is ...

**Comment by plk** [comment]
On second thoughts, the string in the `Value` of the EnumMember attribute also needs addressing - it doesn't double the backslashes and so that's broken too and that's not covered by the PR.

**Comment by plk** [comment]
Or, actually, just changed the enum template to restrict the Value to a literal - I think that is almost certainly what you always want. - I have added that to  the PR.
