### ISSUE TITLE
Asp.NetCore: How can I tell Nswag to use lower case controller names in the API URL?

### ISSUE THREAD

**Issue by SeppPenner** [RSuter/NSwag#1979]
Is there an option to tell NSwag to use lower case controller names in the generation. Right now I get e.g. `api/User/create` from the `UserController` class while it should be `api/user/create`. Or is this an option to set in the ASP.Net Core MVC options?

**Comment by RSuter** [comment]
This is controlled by ASP.NET Core and reported to NSwag, use [Route("user")]

**Comment by SeppPenner** [comment]
Thank you for the fast reply again. I was using `[Route("api/[controller]")]` before. I will simply change it to a fixed value, e.g. `[Route("api/user")]`.

**Comment by ntziolis** [comment]
For anybody looking to get lowercase URLs without having to type out controller names, simply add the following:
```
public void ConfigureServices(IServiceCollection services)
{
  services.AddRouting(options => options.LowercaseUrls = true);
  ...
}
```
Before:
![image](https://user-images.githubusercontent.com/265338/66713521-2a384780-edac-11e9-92b8-dcd1121355a0.png)

After:
![image](https://user-images.githubusercontent.com/265338/66713477-beee7580-edab-11e9-8c7f-a1665778885e.png)

What it does NOT achieve is lowercasing the operation tags (Accounts) as you can see in this screen as you can see in the second picture.

Since asp.net core does at some point report lowercase names, would it be possible to use those lowercase names instead for operation tags as well?

If you point me in the right direction im happy to create a PR.

**Comment by SeppPenner** [comment]
@ntziolis Thanks :D I didn't have that much controllers yet that it was an issue to set the names manually.

**Comment by ntziolis** [comment]
@SeppPenner Any string is an evil string ;)
