### ISSUE TITLE
Ability to pass in KVP for replace into "nswag run MySwaggerConfig.nswag" as an argument.

### ISSUE THREAD

**Issue by ksmithRenweb** [RSuter/NSwag#837]
In essence what I want to be able to do is put something like "{Configuration}" in the .nswag and then as a cmd line parameter like "/replace:{"Configuration": "Debug"}. It would replace all "{Configuration}" in the .nswag with "Debug". (Json array of key valur pairs.)

Right now I am handling this with 1 .nswag per configuration and conditional rules.
But it'd be awesome if the command line could handle this.

Thanks,
Kevin

**Comment by RSuter** [comment]
Why don't you transform the nswag file and create a temp file before calling `run`? I'm not sure whether this should be implemented in NSwag itself... I'm not sure yet if this feature should be built into NSwag - each feature makes to codebase bigger and must be supported forever... 

Also we need to implement this so that we can load and save files without loosing the placeholders - this means we need to replace the just before generating which is much more complicated than just replacing while loading the data.

**Comment by ksmithRenweb** [comment]
Transformation, it is a good thought, but VS and VSTS build don't support json transformations natively. I may dig into SlowCheetah more and see how it's implemented. If it's a nuget and msbuild files. it might work.

If it helps any. I believe this issue might provide a solution for my needs and you've labeled it vNext.
https://github.com/NSwag/NSwag/issues/749

**Comment by RSuter** [comment]
Now supported with /variables:foo=bar and $(foo) in the document and the DefaultVariables setting (.nswag config file)
