### ISSUE TITLE
derived classes not generated

### ISSUE THREAD

**Issue by bothel** [RSuter/NSwag#868]
Hello,
I'm trying to generate a csharp client from the attached schema.
[alpha.txt](https://github.com/RSuter/NSwag/files/1202853/alpha.txt)

using a simple console app in VS2017, and the latest NSwag.CodeGeneration.CSharp nuget package

using System;
using NSwag;
using NSwag.CodeGeneration.CSharp;
using System.IO;

namespace TestNSwag
{
	class Program
	{
		static void Main(string[] args)
		{
			var schema = File.ReadAllText(@"c:\temp\alpha.txt");
			var doc = SwaggerDocument.FromJsonAsync(schema).Result;
			var settings = new SwaggerToCSharpClientGeneratorSettings
			{
				ClassName = "MyClass",
				CSharpGeneratorSettings =
				{
					Namespace = "MyNamespace"
				}
			};

			var generator = new SwaggerToCSharpClientGenerator(doc, settings);
			var code = generator.GenerateFile(NSwag.CodeGeneration.ClientGeneratorOutputType.Full);
		}
	}
}

The code that is emmitted is:
[MyClass.txt](https://github.com/RSuter/NSwag/files/1202855/MyClass.txt)

The intent is that the Recipient and Sender properties of the Piece class could be either a UsAddress or ForeignAddress. The inheritance seems to be partially working in that the Address class has the JsonInheritance attributes for UsAddress and ForeignAddress, however neither the UsAddress of ForeignAddress classes where generated.

Is this a problem in my schema?

**Comment by MChartier** [comment]
I encountered this recently. As near as I can tell, the JsonInheritance attributes are only used to tell the Json serializer how to serialize and deserialize the responses, and is not used to duplicate the derived response classes as part of the generated client code.

I worked around this by using my own defined model classes, including the derived classes, instead of having NSwag generate duplicates. Specifically, I unticked "Generate DTO Types" in NSwagStudio, took a dependency on a separate library which contained them, and added the namespaces to "Additional Namespace Usages" in NSwagStudio.

If anybody knows of a way to ensure that derived classes are included in the generated code, I'd be very interested.

**Comment by RSuter** [comment]
Im pretty sure that this is not working because your discriminator is an enum and not a string. Ill look into this soon.

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/e8b3df6df26a98cd7127d579322c5b292ac3f4fa

**Comment by RSuter** [comment]
Please test with the CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts
